/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#005dac",
        "surface-bright": "#f7f9fc",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#414752",
        "on-secondary-fixed": "#001c3a",
        "surface": "#f7f9fc",
        "outline": "#717783",
        "surface-container": "#eceef1",
        "outline-variant": "#c1c6d4",
        "on-tertiary-fixed-variant": "#733600",
        "on-primary-fixed-variant": "#004786",
        "on-tertiary-fixed": "#311300",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f4f7",
        "surface-tint": "#005faf",
        "surface-container-high": "#e6e8eb",
        "on-tertiary-container": "#fffeff",
        "inverse-on-surface": "#eff1f4",
        "surface-dim": "#d8dadd",
        "on-surface": "#191c1e",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffdbc7",
        "secondary-fixed": "#d4e3ff",
        "on-secondary-container": "#425b7f",
        "primary-container": "#1976d2",
        "secondary": "#475f84",
        "primary-fixed-dim": "#a5c8ff",
        "surface-container-highest": "#e0e3e6",
        "tertiary": "#944700",
        "background": "#f7f9fc",
        "on-secondary-fixed-variant": "#2f486a",
        "tertiary-container": "#ba5b00",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "inverse-primary": "#a5c8ff",
        "secondary-fixed-dim": "#afc8f1",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001c3a",
        "primary-fixed": "#d4e3ff",
        "tertiary-fixed-dim": "#ffb688",
        "on-error": "#ffffff",
        "secondary-container": "#bad3fd",
        "on-error-container": "#93000a",
        "on-primary-container": "#fffdff",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e6",
        "inverse-surface": "#2d3133"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
